kind: Service
apiVersion: v1
metadata:
  name: apigateway-svc
spec:
  type: NodePort
  selector:
    app: apigateway
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  selector:
      matchLabels:
        app: apigateway
  replicas: 1
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: apigateway:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8080