#version: '3'
#services:
#personalrest-server:
#     personalrest-server:
#        container_name: personalrest-server
#        build:
#            context: docker-personalrest-server
#            dockerfile: Dockerfile
#        image: personalrest-server:latest
#        ports:
#            - 18888:8888
#        networks:
#            - spring-cloud-network
#        environment:
#            SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/database?autoReconnect=true&useSSL=false
#            depends_on:
#              - docker-mysql
#     docker-mysql:
#        image: mysql:5.7
#        environment:
#          - MYSQL_ROOT_PASSWORD=root
#          - MYSQL_DATABASE=appquitue
#          - MYSQL_USER=root
#          - MYSQL_PASSWORD=root
#        ports:
#          - 3307:3306
#      
#networks:
#    spring-cloud-network:
#        driver: bridge
#      
version: "3.8"
services:
#  mysqldb:
#    image: mysql:5.7
#    restart: unless-stopped
#    env_file: ./.env
#    environment:
#      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#      - MYSQL_DATABASE=$MYSQLDB_DATABASE
#    ports:
#      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
#    volumes:
#      - db:/var/lib/mysql
  apigateway:
#    depends_on:
#      - mysqldb
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
#    environment:
#      SPRING_APPLICATION_JSON: '{
#        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
#        "spring.datasource.username" : "$MYSQLDB_USER",
#        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
#        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
#        "spring.jpa.hibernate.ddl-auto" : "update"
#      }'
#    volumes:
#      - .m2/:root/.m2
    stdin_open: true
    tty: true
#volumes:
#  db: