version: "3.8"
services:
  missionrest:
    image: missionrest:0.0.1-SNAPSHOT
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    stdin_open: true
    tty: true