kind: Service
apiVersion: v1
metadata:
  name: personalrest
spec:
  selector:
    app: personalrest
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: personalrest
spec:
  selector:
      matchLabels:
        app: personalrest
  replicas: 1
  template:
    metadata:
      labels:
        app: personalrest
    spec:
      containers:
        - name: personalrest
          image: personalrest:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8090